Improve check script

diff --git a/check b/check
--- a/check
+++ b/check
@@ -19,9 +19,11 @@ declare -a crates=(
 
 for crate in "${crates[@]}"
 do
+    echo -e "\ncargo clippy -p $crate --target wasm32-unknown-unknown"
     cargo clippy -p $crate --target wasm32-unknown-unknown
-    if [ $? -ne 0 ]; then
-        echo "\n--> $crate\n"
-        exit $code
+    status=$?
+    if [ $status -ne 0 ]; then
+        echo -e "\n--> wasm32 check of $crate failed\n"
+        exit $status
     fi
 done
