Update ci.yaml

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -45,6 +45,8 @@ jobs:
       - name: Install Crosstool-NG and build toolchain
         if: runner.os == 'Linux'
         run: |
+          cd $GITHUB_WORKSPACE
+          cat .config || echo "No .config file found. It is required to build the toolchain." 
           export PATH=$HOME/.local/share/crosstool-ng/bin:$PATH
           if ! command -v ct-ng; then
             sudo apt-get update
@@ -57,5 +59,4 @@ jobs:
             make install
           fi
           ct-ng --version
-          cat .config || true
           ct-ng build
