Update ci.yaml

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -57,7 +57,15 @@ jobs:
             make install
           fi
           cd $GITHUB_WORKSPACE
-          ct-ng build --silent --quiet
+          ct-ng build >build.log 2>&1
+
+          # Check if ct-ng build was successful
+          if [ $? -eq 0 ]; then
+            echo "Build succeeded"
+          else
+            echo "Build failed, here's the log:"
+            cat build.log
+          fid > build.log 2>&1
 
       - name: Build OpenSSl against musl
         if: runner.os == 'Linux'
