Merge new musl build with old CI, Release builds
- Merges the old CI script with the new musl build.
- Update deploy.yaml to use updated musl toolchain to build musl target for linux.

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -29,7 +29,7 @@ jobs:
       - name: Install stable toolchain
         uses: dtolnay/rust-toolchain@stable
 
-      - name: Cache
+      - name: Cache Cargo Build Outputs
         uses: actions/cache@v3
         with:
           path: |
@@ -40,23 +40,107 @@ jobs:
             target/
           key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
 
-      - name: Install zig on linux
-        if: runner.os == 'Linux'
-        uses: goto-bus-stop/setup-zig@v2 # needed for cargo-zigbuild
+      - name: Cache Toolchain and OpenSSL
+        uses: actions/cache@v4
+        with:
+          path: |
+            ~/x-tools
+            ~/openssl
+          key: ${{ runner.os }}-musl-${{ hashFiles('**/musl-toolchain/.config') }}
+          restore-keys: |
+            ${{ runner.os }}-musl-
 
       - name: Build on Linux
         if: runner.os == 'Linux'
         # We're using musl to make the binaries statically linked and portable
         run: |
-          cargo install cargo-zigbuild
-          cargo --verbose zigbuild --bin kaspad --bin simpa --bin rothschild --bin kaspa-wallet --release --target x86_64-unknown-linux-gnu.2.27 # Use an older glibc version
+          if [ ! -d "$HOME/x-tools" ]; then
+            # Install dependencies
+            sudo apt-get update
+            sudo apt-get install -y autoconf automake libtool libtool-bin unzip help2man python3.10-dev gperf bison flex texinfo gawk libncurses5-dev
+            
+            # Clone crosstool-ng
+            git clone https://github.com/crosstool-ng/crosstool-ng
+            
+            # Configure and build crosstool-ng
+            cd crosstool-ng
+            ./bootstrap
+            ./configure --prefix=$HOME/ctng
+            make
+            make install
+
+            # Add crosstool-ng to PATH
+            export PATH=$HOME/ctng/bin:$PATH
+
+            # Configure and build the musl toolchain
+            cd $GITHUB_WORKSPACE/musl-toolchain
+            ct-ng build > build.log 2>&1
+            
+            # Set status to the exit code of the build
+            status=$?
+            
+            # We store the log in a file because it bloats the screen too much
+            # on GitHub Actions. We print it only if the build fails.
+            echo "Build result:"
+            if [ $status -eq 0 ]; then
+              echo "Build succeeded"
+              ls -la $HOME/x-tools
+            else
+              echo "Build failed, here's the log:"
+              cat build.log
+            fi
+          fi
+          
+          # Update toolchain variables: C compiler, C++ compiler, linker, and archiver
+          export CC=$HOME/x-tools/x86_64-multilib-linux-musl/bin/x86_64-multilib-linux-musl-gcc
+          export CXX=$HOME/x-tools/x86_64-multilib-linux-musl/bin/x86_64-multilib-linux-musl-g++
+          export LD=$HOME/x-tools/x86_64-multilib-linux-musl/bin/x86_64-multilib-linux-musl-ld
+          export AR=$HOME/x-tools/x86_64-multilib-linux-musl/bin/x86_64-multilib-linux-musl-ar        
+          
+          # Check if "$HOME/openssl" directory exists from cache
+          if [ ! -d "$HOME/openssl" ]; then
+            wget https://www.openssl.org/source/openssl-1.1.1l.tar.gz
+            tar xzf openssl-1.1.1l.tar.gz
+            cd openssl-1.1.1l
+            # Configure OpenSSL for static linking
+            ./Configure no-shared --static linux-x86_64 -fPIC --prefix=$HOME/openssl
+            make depend
+            make
+            make install
+            # Check if OpenSSL was installed successfully
+            ls -la $HOME/openssl
+          fi
+          
+          # Set environment variables for static linking
+          export OPENSSL_DIR=$HOME/openssl
+          export OPENSSL_STATIC=true
+          export RUSTFLAGS="-C link-arg=-static -C link-arg=-L$OPENSSL_DIR/lib"
+
+          # We specify the compiler that will invoke linker
+          export CARGO_TARGET_X86_64_UNKNOWN_LINUX_MUSL_LINKER=$CC
+
+          # Add target
+          rustup target add x86_64-unknown-linux-musl
+
+          # Install missing dependencies
+          cargo fetch --target x86_64-unknown-linux-musl
+
+          # Patch missing include in librocksdb-sys-0.16.0+8.10.0. Credit: @supertypo
+          FILE_PATH=$(find $HOME/.cargo/registry/src/ -path "*/librocksdb-sys-0.16.0+8.10.0/*/offpeak_time_info.h")
+          if [ -n "$FILE_PATH" ]; then
+            sed -i '1i #include <cstdint>' "$FILE_PATH"
+          else
+            echo "No such file for sed modification."
+          fi
+
+          # Build for musl
+          cargo --verbose build --bin kaspad --bin rothschild --bin kaspa-wallet --release --target x86_64-unknown-linux-musl
           mkdir bin || true
-          cp target/x86_64-unknown-linux-gnu/release/kaspad bin/
-          cp target/x86_64-unknown-linux-gnu/release/simpa bin/
-          cp target/x86_64-unknown-linux-gnu/release/rothschild bin/
-          cp target/x86_64-unknown-linux-gnu/release/kaspa-wallet bin/
-          archive="bin/rusty-kaspa-${{ github.event.release.tag_name }}-linux-gnu-amd64.zip"
-          asset_name="rusty-kaspa-${{ github.event.release.tag_name }}-linux-gnu-amd64.zip"
+          cp target/x86_64-unknown-linux-musl/release/kaspad bin/
+          cp target/x86_64-unknown-linux-musl/release/rothschild bin/
+          cp target/x86_64-unknown-linux-musl/release/kaspa-wallet bin/
+          archive="bin/rusty-kaspa-${{ github.event.release.tag_name }}-linux-musl-amd64.zip"
+          asset_name="rusty-kaspa-${{ github.event.release.tag_name }}-linux-musl-amd64.zip"
           zip -r "${archive}" ./bin/*
           echo "archive=${archive}" >> $GITHUB_ENV
           echo "asset_name=${asset_name}" >> $GITHUB_ENV
